// <auto-generated />
namespace CEMEX.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddschemaentityError : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddschemaentityError));
        
        string IMigrationMetadata.Id
        {
            get { return "201706091809011_Add schema entity Error"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
